
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Person` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Person
 * 
 */
export type PersonModel = runtime.Types.Result.DefaultSelection<Prisma.$PersonPayload>

export type AggregatePerson = {
  _count: PersonCountAggregateOutputType | null
  _avg: PersonAvgAggregateOutputType | null
  _sum: PersonSumAggregateOutputType | null
  _min: PersonMinAggregateOutputType | null
  _max: PersonMaxAggregateOutputType | null
}

export type PersonAvgAggregateOutputType = {
  id: number | null
}

export type PersonSumAggregateOutputType = {
  id: number | null
}

export type PersonMinAggregateOutputType = {
  id: number | null
  fullName: string | null
  birthDay: Date | null
}

export type PersonMaxAggregateOutputType = {
  id: number | null
  fullName: string | null
  birthDay: Date | null
}

export type PersonCountAggregateOutputType = {
  id: number
  fullName: number
  birthDay: number
  _all: number
}


export type PersonAvgAggregateInputType = {
  id?: true
}

export type PersonSumAggregateInputType = {
  id?: true
}

export type PersonMinAggregateInputType = {
  id?: true
  fullName?: true
  birthDay?: true
}

export type PersonMaxAggregateInputType = {
  id?: true
  fullName?: true
  birthDay?: true
}

export type PersonCountAggregateInputType = {
  id?: true
  fullName?: true
  birthDay?: true
  _all?: true
}

export type PersonAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Person to aggregate.
   */
  where?: Prisma.PersonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of People to fetch.
   */
  orderBy?: Prisma.PersonOrderByWithRelationInput | Prisma.PersonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PersonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` People from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` People.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned People
  **/
  _count?: true | PersonCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PersonAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PersonSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PersonMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PersonMaxAggregateInputType
}

export type GetPersonAggregateType<T extends PersonAggregateArgs> = {
      [P in keyof T & keyof AggregatePerson]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePerson[P]>
    : Prisma.GetScalarType<T[P], AggregatePerson[P]>
}




export type PersonGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PersonWhereInput
  orderBy?: Prisma.PersonOrderByWithAggregationInput | Prisma.PersonOrderByWithAggregationInput[]
  by: Prisma.PersonScalarFieldEnum[] | Prisma.PersonScalarFieldEnum
  having?: Prisma.PersonScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PersonCountAggregateInputType | true
  _avg?: PersonAvgAggregateInputType
  _sum?: PersonSumAggregateInputType
  _min?: PersonMinAggregateInputType
  _max?: PersonMaxAggregateInputType
}

export type PersonGroupByOutputType = {
  id: number
  fullName: string
  birthDay: Date
  _count: PersonCountAggregateOutputType | null
  _avg: PersonAvgAggregateOutputType | null
  _sum: PersonSumAggregateOutputType | null
  _min: PersonMinAggregateOutputType | null
  _max: PersonMaxAggregateOutputType | null
}

export type GetPersonGroupByPayload<T extends PersonGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PersonGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PersonGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PersonGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PersonGroupByOutputType[P]>
      }
    >
  >



export type PersonWhereInput = {
  AND?: Prisma.PersonWhereInput | Prisma.PersonWhereInput[]
  OR?: Prisma.PersonWhereInput[]
  NOT?: Prisma.PersonWhereInput | Prisma.PersonWhereInput[]
  id?: Prisma.IntFilter<"Person"> | number
  fullName?: Prisma.StringFilter<"Person"> | string
  birthDay?: Prisma.DateTimeFilter<"Person"> | Date | string
  booking?: Prisma.BookingListRelationFilter
  worker?: Prisma.XOR<Prisma.WorkerNullableScalarRelationFilter, Prisma.WorkerWhereInput> | null
}

export type PersonOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  birthDay?: Prisma.SortOrder
  booking?: Prisma.BookingOrderByRelationAggregateInput
  worker?: Prisma.WorkerOrderByWithRelationInput
  _relevance?: Prisma.PersonOrderByRelevanceInput
}

export type PersonWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.PersonWhereInput | Prisma.PersonWhereInput[]
  OR?: Prisma.PersonWhereInput[]
  NOT?: Prisma.PersonWhereInput | Prisma.PersonWhereInput[]
  fullName?: Prisma.StringFilter<"Person"> | string
  birthDay?: Prisma.DateTimeFilter<"Person"> | Date | string
  booking?: Prisma.BookingListRelationFilter
  worker?: Prisma.XOR<Prisma.WorkerNullableScalarRelationFilter, Prisma.WorkerWhereInput> | null
}, "id">

export type PersonOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  birthDay?: Prisma.SortOrder
  _count?: Prisma.PersonCountOrderByAggregateInput
  _avg?: Prisma.PersonAvgOrderByAggregateInput
  _max?: Prisma.PersonMaxOrderByAggregateInput
  _min?: Prisma.PersonMinOrderByAggregateInput
  _sum?: Prisma.PersonSumOrderByAggregateInput
}

export type PersonScalarWhereWithAggregatesInput = {
  AND?: Prisma.PersonScalarWhereWithAggregatesInput | Prisma.PersonScalarWhereWithAggregatesInput[]
  OR?: Prisma.PersonScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PersonScalarWhereWithAggregatesInput | Prisma.PersonScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Person"> | number
  fullName?: Prisma.StringWithAggregatesFilter<"Person"> | string
  birthDay?: Prisma.DateTimeWithAggregatesFilter<"Person"> | Date | string
}

export type PersonCreateInput = {
  id: number
  fullName: string
  birthDay: Date | string
  booking?: Prisma.BookingCreateNestedManyWithoutPersonInput
  worker?: Prisma.WorkerCreateNestedOneWithoutPersonInput
}

export type PersonUncheckedCreateInput = {
  id: number
  fullName: string
  birthDay: Date | string
  booking?: Prisma.BookingUncheckedCreateNestedManyWithoutPersonInput
  worker?: Prisma.WorkerUncheckedCreateNestedOneWithoutPersonInput
}

export type PersonUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  birthDay?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  booking?: Prisma.BookingUpdateManyWithoutPersonNestedInput
  worker?: Prisma.WorkerUpdateOneWithoutPersonNestedInput
}

export type PersonUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  birthDay?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  booking?: Prisma.BookingUncheckedUpdateManyWithoutPersonNestedInput
  worker?: Prisma.WorkerUncheckedUpdateOneWithoutPersonNestedInput
}

export type PersonCreateManyInput = {
  id: number
  fullName: string
  birthDay: Date | string
}

export type PersonUpdateManyMutationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  birthDay?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PersonUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  birthDay?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PersonScalarRelationFilter = {
  is?: Prisma.PersonWhereInput
  isNot?: Prisma.PersonWhereInput
}

export type PersonOrderByRelevanceInput = {
  fields: Prisma.PersonOrderByRelevanceFieldEnum | Prisma.PersonOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type PersonCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  birthDay?: Prisma.SortOrder
}

export type PersonAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type PersonMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  birthDay?: Prisma.SortOrder
}

export type PersonMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  birthDay?: Prisma.SortOrder
}

export type PersonSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type PersonCreateNestedOneWithoutBookingInput = {
  create?: Prisma.XOR<Prisma.PersonCreateWithoutBookingInput, Prisma.PersonUncheckedCreateWithoutBookingInput>
  connectOrCreate?: Prisma.PersonCreateOrConnectWithoutBookingInput
  connect?: Prisma.PersonWhereUniqueInput
}

export type PersonUpdateOneRequiredWithoutBookingNestedInput = {
  create?: Prisma.XOR<Prisma.PersonCreateWithoutBookingInput, Prisma.PersonUncheckedCreateWithoutBookingInput>
  connectOrCreate?: Prisma.PersonCreateOrConnectWithoutBookingInput
  upsert?: Prisma.PersonUpsertWithoutBookingInput
  connect?: Prisma.PersonWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PersonUpdateToOneWithWhereWithoutBookingInput, Prisma.PersonUpdateWithoutBookingInput>, Prisma.PersonUncheckedUpdateWithoutBookingInput>
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type PersonCreateNestedOneWithoutWorkerInput = {
  create?: Prisma.XOR<Prisma.PersonCreateWithoutWorkerInput, Prisma.PersonUncheckedCreateWithoutWorkerInput>
  connectOrCreate?: Prisma.PersonCreateOrConnectWithoutWorkerInput
  connect?: Prisma.PersonWhereUniqueInput
}

export type PersonUpdateOneRequiredWithoutWorkerNestedInput = {
  create?: Prisma.XOR<Prisma.PersonCreateWithoutWorkerInput, Prisma.PersonUncheckedCreateWithoutWorkerInput>
  connectOrCreate?: Prisma.PersonCreateOrConnectWithoutWorkerInput
  upsert?: Prisma.PersonUpsertWithoutWorkerInput
  connect?: Prisma.PersonWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PersonUpdateToOneWithWhereWithoutWorkerInput, Prisma.PersonUpdateWithoutWorkerInput>, Prisma.PersonUncheckedUpdateWithoutWorkerInput>
}

export type PersonCreateWithoutBookingInput = {
  id: number
  fullName: string
  birthDay: Date | string
  worker?: Prisma.WorkerCreateNestedOneWithoutPersonInput
}

export type PersonUncheckedCreateWithoutBookingInput = {
  id: number
  fullName: string
  birthDay: Date | string
  worker?: Prisma.WorkerUncheckedCreateNestedOneWithoutPersonInput
}

export type PersonCreateOrConnectWithoutBookingInput = {
  where: Prisma.PersonWhereUniqueInput
  create: Prisma.XOR<Prisma.PersonCreateWithoutBookingInput, Prisma.PersonUncheckedCreateWithoutBookingInput>
}

export type PersonUpsertWithoutBookingInput = {
  update: Prisma.XOR<Prisma.PersonUpdateWithoutBookingInput, Prisma.PersonUncheckedUpdateWithoutBookingInput>
  create: Prisma.XOR<Prisma.PersonCreateWithoutBookingInput, Prisma.PersonUncheckedCreateWithoutBookingInput>
  where?: Prisma.PersonWhereInput
}

export type PersonUpdateToOneWithWhereWithoutBookingInput = {
  where?: Prisma.PersonWhereInput
  data: Prisma.XOR<Prisma.PersonUpdateWithoutBookingInput, Prisma.PersonUncheckedUpdateWithoutBookingInput>
}

export type PersonUpdateWithoutBookingInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  birthDay?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  worker?: Prisma.WorkerUpdateOneWithoutPersonNestedInput
}

export type PersonUncheckedUpdateWithoutBookingInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  birthDay?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  worker?: Prisma.WorkerUncheckedUpdateOneWithoutPersonNestedInput
}

export type PersonCreateWithoutWorkerInput = {
  id: number
  fullName: string
  birthDay: Date | string
  booking?: Prisma.BookingCreateNestedManyWithoutPersonInput
}

export type PersonUncheckedCreateWithoutWorkerInput = {
  id: number
  fullName: string
  birthDay: Date | string
  booking?: Prisma.BookingUncheckedCreateNestedManyWithoutPersonInput
}

export type PersonCreateOrConnectWithoutWorkerInput = {
  where: Prisma.PersonWhereUniqueInput
  create: Prisma.XOR<Prisma.PersonCreateWithoutWorkerInput, Prisma.PersonUncheckedCreateWithoutWorkerInput>
}

export type PersonUpsertWithoutWorkerInput = {
  update: Prisma.XOR<Prisma.PersonUpdateWithoutWorkerInput, Prisma.PersonUncheckedUpdateWithoutWorkerInput>
  create: Prisma.XOR<Prisma.PersonCreateWithoutWorkerInput, Prisma.PersonUncheckedCreateWithoutWorkerInput>
  where?: Prisma.PersonWhereInput
}

export type PersonUpdateToOneWithWhereWithoutWorkerInput = {
  where?: Prisma.PersonWhereInput
  data: Prisma.XOR<Prisma.PersonUpdateWithoutWorkerInput, Prisma.PersonUncheckedUpdateWithoutWorkerInput>
}

export type PersonUpdateWithoutWorkerInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  birthDay?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  booking?: Prisma.BookingUpdateManyWithoutPersonNestedInput
}

export type PersonUncheckedUpdateWithoutWorkerInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  birthDay?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  booking?: Prisma.BookingUncheckedUpdateManyWithoutPersonNestedInput
}


/**
 * Count Type PersonCountOutputType
 */

export type PersonCountOutputType = {
  booking: number
}

export type PersonCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  booking?: boolean | PersonCountOutputTypeCountBookingArgs
}

/**
 * PersonCountOutputType without action
 */
export type PersonCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonCountOutputType
   */
  select?: Prisma.PersonCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PersonCountOutputType without action
 */
export type PersonCountOutputTypeCountBookingArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BookingWhereInput
}


export type PersonSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fullName?: boolean
  birthDay?: boolean
  booking?: boolean | Prisma.Person$bookingArgs<ExtArgs>
  worker?: boolean | Prisma.Person$workerArgs<ExtArgs>
  _count?: boolean | Prisma.PersonCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["person"]>



export type PersonSelectScalar = {
  id?: boolean
  fullName?: boolean
  birthDay?: boolean
}

export type PersonOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fullName" | "birthDay", ExtArgs["result"]["person"]>
export type PersonInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  booking?: boolean | Prisma.Person$bookingArgs<ExtArgs>
  worker?: boolean | Prisma.Person$workerArgs<ExtArgs>
  _count?: boolean | Prisma.PersonCountOutputTypeDefaultArgs<ExtArgs>
}

export type $PersonPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Person"
  objects: {
    booking: Prisma.$BookingPayload<ExtArgs>[]
    worker: Prisma.$WorkerPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    fullName: string
    birthDay: Date
  }, ExtArgs["result"]["person"]>
  composites: {}
}

export type PersonGetPayload<S extends boolean | null | undefined | PersonDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PersonPayload, S>

export type PersonCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PersonFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PersonCountAggregateInputType | true
  }

export interface PersonDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Person'], meta: { name: 'Person' } }
  /**
   * Find zero or one Person that matches the filter.
   * @param {PersonFindUniqueArgs} args - Arguments to find a Person
   * @example
   * // Get one Person
   * const person = await prisma.person.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PersonFindUniqueArgs>(args: Prisma.SelectSubset<T, PersonFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Person that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PersonFindUniqueOrThrowArgs} args - Arguments to find a Person
   * @example
   * // Get one Person
   * const person = await prisma.person.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PersonFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PersonFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Person that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonFindFirstArgs} args - Arguments to find a Person
   * @example
   * // Get one Person
   * const person = await prisma.person.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PersonFindFirstArgs>(args?: Prisma.SelectSubset<T, PersonFindFirstArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Person that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonFindFirstOrThrowArgs} args - Arguments to find a Person
   * @example
   * // Get one Person
   * const person = await prisma.person.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PersonFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PersonFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more People that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all People
   * const people = await prisma.person.findMany()
   * 
   * // Get first 10 People
   * const people = await prisma.person.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const personWithIdOnly = await prisma.person.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PersonFindManyArgs>(args?: Prisma.SelectSubset<T, PersonFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Person.
   * @param {PersonCreateArgs} args - Arguments to create a Person.
   * @example
   * // Create one Person
   * const Person = await prisma.person.create({
   *   data: {
   *     // ... data to create a Person
   *   }
   * })
   * 
   */
  create<T extends PersonCreateArgs>(args: Prisma.SelectSubset<T, PersonCreateArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many People.
   * @param {PersonCreateManyArgs} args - Arguments to create many People.
   * @example
   * // Create many People
   * const person = await prisma.person.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PersonCreateManyArgs>(args?: Prisma.SelectSubset<T, PersonCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Person.
   * @param {PersonDeleteArgs} args - Arguments to delete one Person.
   * @example
   * // Delete one Person
   * const Person = await prisma.person.delete({
   *   where: {
   *     // ... filter to delete one Person
   *   }
   * })
   * 
   */
  delete<T extends PersonDeleteArgs>(args: Prisma.SelectSubset<T, PersonDeleteArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Person.
   * @param {PersonUpdateArgs} args - Arguments to update one Person.
   * @example
   * // Update one Person
   * const person = await prisma.person.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PersonUpdateArgs>(args: Prisma.SelectSubset<T, PersonUpdateArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more People.
   * @param {PersonDeleteManyArgs} args - Arguments to filter People to delete.
   * @example
   * // Delete a few People
   * const { count } = await prisma.person.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PersonDeleteManyArgs>(args?: Prisma.SelectSubset<T, PersonDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more People.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many People
   * const person = await prisma.person.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PersonUpdateManyArgs>(args: Prisma.SelectSubset<T, PersonUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Person.
   * @param {PersonUpsertArgs} args - Arguments to update or create a Person.
   * @example
   * // Update or create a Person
   * const person = await prisma.person.upsert({
   *   create: {
   *     // ... data to create a Person
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Person we want to update
   *   }
   * })
   */
  upsert<T extends PersonUpsertArgs>(args: Prisma.SelectSubset<T, PersonUpsertArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of People.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonCountArgs} args - Arguments to filter People to count.
   * @example
   * // Count the number of People
   * const count = await prisma.person.count({
   *   where: {
   *     // ... the filter for the People we want to count
   *   }
   * })
  **/
  count<T extends PersonCountArgs>(
    args?: Prisma.Subset<T, PersonCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PersonCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Person.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PersonAggregateArgs>(args: Prisma.Subset<T, PersonAggregateArgs>): Prisma.PrismaPromise<GetPersonAggregateType<T>>

  /**
   * Group by Person.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PersonGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PersonGroupByArgs['orderBy'] }
      : { orderBy?: PersonGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PersonGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPersonGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Person model
 */
readonly fields: PersonFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Person.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PersonClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  booking<T extends Prisma.Person$bookingArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Person$bookingArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BookingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  worker<T extends Prisma.Person$workerArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Person$workerArgs<ExtArgs>>): Prisma.Prisma__WorkerClient<runtime.Types.Result.GetResult<Prisma.$WorkerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Person model
 */
export interface PersonFieldRefs {
  readonly id: Prisma.FieldRef<"Person", 'Int'>
  readonly fullName: Prisma.FieldRef<"Person", 'String'>
  readonly birthDay: Prisma.FieldRef<"Person", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Person findUnique
 */
export type PersonFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * Filter, which Person to fetch.
   */
  where: Prisma.PersonWhereUniqueInput
}

/**
 * Person findUniqueOrThrow
 */
export type PersonFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * Filter, which Person to fetch.
   */
  where: Prisma.PersonWhereUniqueInput
}

/**
 * Person findFirst
 */
export type PersonFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * Filter, which Person to fetch.
   */
  where?: Prisma.PersonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of People to fetch.
   */
  orderBy?: Prisma.PersonOrderByWithRelationInput | Prisma.PersonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for People.
   */
  cursor?: Prisma.PersonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` People from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` People.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of People.
   */
  distinct?: Prisma.PersonScalarFieldEnum | Prisma.PersonScalarFieldEnum[]
}

/**
 * Person findFirstOrThrow
 */
export type PersonFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * Filter, which Person to fetch.
   */
  where?: Prisma.PersonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of People to fetch.
   */
  orderBy?: Prisma.PersonOrderByWithRelationInput | Prisma.PersonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for People.
   */
  cursor?: Prisma.PersonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` People from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` People.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of People.
   */
  distinct?: Prisma.PersonScalarFieldEnum | Prisma.PersonScalarFieldEnum[]
}

/**
 * Person findMany
 */
export type PersonFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * Filter, which People to fetch.
   */
  where?: Prisma.PersonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of People to fetch.
   */
  orderBy?: Prisma.PersonOrderByWithRelationInput | Prisma.PersonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing People.
   */
  cursor?: Prisma.PersonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` People from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` People.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of People.
   */
  distinct?: Prisma.PersonScalarFieldEnum | Prisma.PersonScalarFieldEnum[]
}

/**
 * Person create
 */
export type PersonCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * The data needed to create a Person.
   */
  data: Prisma.XOR<Prisma.PersonCreateInput, Prisma.PersonUncheckedCreateInput>
}

/**
 * Person createMany
 */
export type PersonCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many People.
   */
  data: Prisma.PersonCreateManyInput | Prisma.PersonCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Person update
 */
export type PersonUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * The data needed to update a Person.
   */
  data: Prisma.XOR<Prisma.PersonUpdateInput, Prisma.PersonUncheckedUpdateInput>
  /**
   * Choose, which Person to update.
   */
  where: Prisma.PersonWhereUniqueInput
}

/**
 * Person updateMany
 */
export type PersonUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update People.
   */
  data: Prisma.XOR<Prisma.PersonUpdateManyMutationInput, Prisma.PersonUncheckedUpdateManyInput>
  /**
   * Filter which People to update
   */
  where?: Prisma.PersonWhereInput
  /**
   * Limit how many People to update.
   */
  limit?: number
}

/**
 * Person upsert
 */
export type PersonUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * The filter to search for the Person to update in case it exists.
   */
  where: Prisma.PersonWhereUniqueInput
  /**
   * In case the Person found by the `where` argument doesn't exist, create a new Person with this data.
   */
  create: Prisma.XOR<Prisma.PersonCreateInput, Prisma.PersonUncheckedCreateInput>
  /**
   * In case the Person was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PersonUpdateInput, Prisma.PersonUncheckedUpdateInput>
}

/**
 * Person delete
 */
export type PersonDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
  /**
   * Filter which Person to delete.
   */
  where: Prisma.PersonWhereUniqueInput
}

/**
 * Person deleteMany
 */
export type PersonDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which People to delete
   */
  where?: Prisma.PersonWhereInput
  /**
   * Limit how many People to delete.
   */
  limit?: number
}

/**
 * Person.booking
 */
export type Person$bookingArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Booking
   */
  select?: Prisma.BookingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Booking
   */
  omit?: Prisma.BookingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingInclude<ExtArgs> | null
  where?: Prisma.BookingWhereInput
  orderBy?: Prisma.BookingOrderByWithRelationInput | Prisma.BookingOrderByWithRelationInput[]
  cursor?: Prisma.BookingWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BookingScalarFieldEnum | Prisma.BookingScalarFieldEnum[]
}

/**
 * Person.worker
 */
export type Person$workerArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Worker
   */
  select?: Prisma.WorkerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Worker
   */
  omit?: Prisma.WorkerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkerInclude<ExtArgs> | null
  where?: Prisma.WorkerWhereInput
}

/**
 * Person without action
 */
export type PersonDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Person
   */
  select?: Prisma.PersonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Person
   */
  omit?: Prisma.PersonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonInclude<ExtArgs> | null
}
