
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Worker` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Worker
 * 
 */
export type WorkerModel = runtime.Types.Result.DefaultSelection<Prisma.$WorkerPayload>

export type AggregateWorker = {
  _count: WorkerCountAggregateOutputType | null
  _avg: WorkerAvgAggregateOutputType | null
  _sum: WorkerSumAggregateOutputType | null
  _min: WorkerMinAggregateOutputType | null
  _max: WorkerMaxAggregateOutputType | null
}

export type WorkerAvgAggregateOutputType = {
  personId: number | null
}

export type WorkerSumAggregateOutputType = {
  personId: number | null
}

export type WorkerMinAggregateOutputType = {
  personId: number | null
  role: $Enums.worker_role | null
  nickName: string | null
  password: string | null
}

export type WorkerMaxAggregateOutputType = {
  personId: number | null
  role: $Enums.worker_role | null
  nickName: string | null
  password: string | null
}

export type WorkerCountAggregateOutputType = {
  personId: number
  role: number
  nickName: number
  password: number
  _all: number
}


export type WorkerAvgAggregateInputType = {
  personId?: true
}

export type WorkerSumAggregateInputType = {
  personId?: true
}

export type WorkerMinAggregateInputType = {
  personId?: true
  role?: true
  nickName?: true
  password?: true
}

export type WorkerMaxAggregateInputType = {
  personId?: true
  role?: true
  nickName?: true
  password?: true
}

export type WorkerCountAggregateInputType = {
  personId?: true
  role?: true
  nickName?: true
  password?: true
  _all?: true
}

export type WorkerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Worker to aggregate.
   */
  where?: Prisma.WorkerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Workers to fetch.
   */
  orderBy?: Prisma.WorkerOrderByWithRelationInput | Prisma.WorkerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorkerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Workers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Workers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Workers
  **/
  _count?: true | WorkerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WorkerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WorkerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorkerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorkerMaxAggregateInputType
}

export type GetWorkerAggregateType<T extends WorkerAggregateArgs> = {
      [P in keyof T & keyof AggregateWorker]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorker[P]>
    : Prisma.GetScalarType<T[P], AggregateWorker[P]>
}




export type WorkerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkerWhereInput
  orderBy?: Prisma.WorkerOrderByWithAggregationInput | Prisma.WorkerOrderByWithAggregationInput[]
  by: Prisma.WorkerScalarFieldEnum[] | Prisma.WorkerScalarFieldEnum
  having?: Prisma.WorkerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorkerCountAggregateInputType | true
  _avg?: WorkerAvgAggregateInputType
  _sum?: WorkerSumAggregateInputType
  _min?: WorkerMinAggregateInputType
  _max?: WorkerMaxAggregateInputType
}

export type WorkerGroupByOutputType = {
  personId: number
  role: $Enums.worker_role
  nickName: string
  password: string
  _count: WorkerCountAggregateOutputType | null
  _avg: WorkerAvgAggregateOutputType | null
  _sum: WorkerSumAggregateOutputType | null
  _min: WorkerMinAggregateOutputType | null
  _max: WorkerMaxAggregateOutputType | null
}

export type GetWorkerGroupByPayload<T extends WorkerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorkerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorkerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorkerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorkerGroupByOutputType[P]>
      }
    >
  >



export type WorkerWhereInput = {
  AND?: Prisma.WorkerWhereInput | Prisma.WorkerWhereInput[]
  OR?: Prisma.WorkerWhereInput[]
  NOT?: Prisma.WorkerWhereInput | Prisma.WorkerWhereInput[]
  personId?: Prisma.IntFilter<"Worker"> | number
  role?: Prisma.Enumworker_roleFilter<"Worker"> | $Enums.worker_role
  nickName?: Prisma.StringFilter<"Worker"> | string
  password?: Prisma.StringFilter<"Worker"> | string
  person?: Prisma.XOR<Prisma.PersonScalarRelationFilter, Prisma.PersonWhereInput>
  bookings?: Prisma.BookingListRelationFilter
}

export type WorkerOrderByWithRelationInput = {
  personId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  nickName?: Prisma.SortOrder
  password?: Prisma.SortOrder
  person?: Prisma.PersonOrderByWithRelationInput
  bookings?: Prisma.BookingOrderByRelationAggregateInput
  _relevance?: Prisma.WorkerOrderByRelevanceInput
}

export type WorkerWhereUniqueInput = Prisma.AtLeast<{
  personId?: number
  nickName?: string
  password?: string
  AND?: Prisma.WorkerWhereInput | Prisma.WorkerWhereInput[]
  OR?: Prisma.WorkerWhereInput[]
  NOT?: Prisma.WorkerWhereInput | Prisma.WorkerWhereInput[]
  role?: Prisma.Enumworker_roleFilter<"Worker"> | $Enums.worker_role
  person?: Prisma.XOR<Prisma.PersonScalarRelationFilter, Prisma.PersonWhereInput>
  bookings?: Prisma.BookingListRelationFilter
}, "personId" | "nickName" | "password">

export type WorkerOrderByWithAggregationInput = {
  personId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  nickName?: Prisma.SortOrder
  password?: Prisma.SortOrder
  _count?: Prisma.WorkerCountOrderByAggregateInput
  _avg?: Prisma.WorkerAvgOrderByAggregateInput
  _max?: Prisma.WorkerMaxOrderByAggregateInput
  _min?: Prisma.WorkerMinOrderByAggregateInput
  _sum?: Prisma.WorkerSumOrderByAggregateInput
}

export type WorkerScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorkerScalarWhereWithAggregatesInput | Prisma.WorkerScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorkerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorkerScalarWhereWithAggregatesInput | Prisma.WorkerScalarWhereWithAggregatesInput[]
  personId?: Prisma.IntWithAggregatesFilter<"Worker"> | number
  role?: Prisma.Enumworker_roleWithAggregatesFilter<"Worker"> | $Enums.worker_role
  nickName?: Prisma.StringWithAggregatesFilter<"Worker"> | string
  password?: Prisma.StringWithAggregatesFilter<"Worker"> | string
}

export type WorkerCreateInput = {
  role?: $Enums.worker_role
  nickName: string
  password: string
  person: Prisma.PersonCreateNestedOneWithoutWorkerInput
  bookings?: Prisma.BookingCreateNestedManyWithoutWorkerInput
}

export type WorkerUncheckedCreateInput = {
  personId: number
  role?: $Enums.worker_role
  nickName: string
  password: string
  bookings?: Prisma.BookingUncheckedCreateNestedManyWithoutWorkerInput
}

export type WorkerUpdateInput = {
  role?: Prisma.Enumworker_roleFieldUpdateOperationsInput | $Enums.worker_role
  nickName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  person?: Prisma.PersonUpdateOneRequiredWithoutWorkerNestedInput
  bookings?: Prisma.BookingUpdateManyWithoutWorkerNestedInput
}

export type WorkerUncheckedUpdateInput = {
  personId?: Prisma.IntFieldUpdateOperationsInput | number
  role?: Prisma.Enumworker_roleFieldUpdateOperationsInput | $Enums.worker_role
  nickName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bookings?: Prisma.BookingUncheckedUpdateManyWithoutWorkerNestedInput
}

export type WorkerCreateManyInput = {
  personId: number
  role?: $Enums.worker_role
  nickName: string
  password: string
}

export type WorkerUpdateManyMutationInput = {
  role?: Prisma.Enumworker_roleFieldUpdateOperationsInput | $Enums.worker_role
  nickName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorkerUncheckedUpdateManyInput = {
  personId?: Prisma.IntFieldUpdateOperationsInput | number
  role?: Prisma.Enumworker_roleFieldUpdateOperationsInput | $Enums.worker_role
  nickName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorkerScalarRelationFilter = {
  is?: Prisma.WorkerWhereInput
  isNot?: Prisma.WorkerWhereInput
}

export type WorkerNullableScalarRelationFilter = {
  is?: Prisma.WorkerWhereInput | null
  isNot?: Prisma.WorkerWhereInput | null
}

export type WorkerOrderByRelevanceInput = {
  fields: Prisma.WorkerOrderByRelevanceFieldEnum | Prisma.WorkerOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type WorkerCountOrderByAggregateInput = {
  personId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  nickName?: Prisma.SortOrder
  password?: Prisma.SortOrder
}

export type WorkerAvgOrderByAggregateInput = {
  personId?: Prisma.SortOrder
}

export type WorkerMaxOrderByAggregateInput = {
  personId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  nickName?: Prisma.SortOrder
  password?: Prisma.SortOrder
}

export type WorkerMinOrderByAggregateInput = {
  personId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  nickName?: Prisma.SortOrder
  password?: Prisma.SortOrder
}

export type WorkerSumOrderByAggregateInput = {
  personId?: Prisma.SortOrder
}

export type WorkerCreateNestedOneWithoutBookingsInput = {
  create?: Prisma.XOR<Prisma.WorkerCreateWithoutBookingsInput, Prisma.WorkerUncheckedCreateWithoutBookingsInput>
  connectOrCreate?: Prisma.WorkerCreateOrConnectWithoutBookingsInput
  connect?: Prisma.WorkerWhereUniqueInput
}

export type WorkerUpdateOneRequiredWithoutBookingsNestedInput = {
  create?: Prisma.XOR<Prisma.WorkerCreateWithoutBookingsInput, Prisma.WorkerUncheckedCreateWithoutBookingsInput>
  connectOrCreate?: Prisma.WorkerCreateOrConnectWithoutBookingsInput
  upsert?: Prisma.WorkerUpsertWithoutBookingsInput
  connect?: Prisma.WorkerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.WorkerUpdateToOneWithWhereWithoutBookingsInput, Prisma.WorkerUpdateWithoutBookingsInput>, Prisma.WorkerUncheckedUpdateWithoutBookingsInput>
}

export type WorkerCreateNestedOneWithoutPersonInput = {
  create?: Prisma.XOR<Prisma.WorkerCreateWithoutPersonInput, Prisma.WorkerUncheckedCreateWithoutPersonInput>
  connectOrCreate?: Prisma.WorkerCreateOrConnectWithoutPersonInput
  connect?: Prisma.WorkerWhereUniqueInput
}

export type WorkerUncheckedCreateNestedOneWithoutPersonInput = {
  create?: Prisma.XOR<Prisma.WorkerCreateWithoutPersonInput, Prisma.WorkerUncheckedCreateWithoutPersonInput>
  connectOrCreate?: Prisma.WorkerCreateOrConnectWithoutPersonInput
  connect?: Prisma.WorkerWhereUniqueInput
}

export type WorkerUpdateOneWithoutPersonNestedInput = {
  create?: Prisma.XOR<Prisma.WorkerCreateWithoutPersonInput, Prisma.WorkerUncheckedCreateWithoutPersonInput>
  connectOrCreate?: Prisma.WorkerCreateOrConnectWithoutPersonInput
  upsert?: Prisma.WorkerUpsertWithoutPersonInput
  disconnect?: Prisma.WorkerWhereInput | boolean
  delete?: Prisma.WorkerWhereInput | boolean
  connect?: Prisma.WorkerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.WorkerUpdateToOneWithWhereWithoutPersonInput, Prisma.WorkerUpdateWithoutPersonInput>, Prisma.WorkerUncheckedUpdateWithoutPersonInput>
}

export type WorkerUncheckedUpdateOneWithoutPersonNestedInput = {
  create?: Prisma.XOR<Prisma.WorkerCreateWithoutPersonInput, Prisma.WorkerUncheckedCreateWithoutPersonInput>
  connectOrCreate?: Prisma.WorkerCreateOrConnectWithoutPersonInput
  upsert?: Prisma.WorkerUpsertWithoutPersonInput
  disconnect?: Prisma.WorkerWhereInput | boolean
  delete?: Prisma.WorkerWhereInput | boolean
  connect?: Prisma.WorkerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.WorkerUpdateToOneWithWhereWithoutPersonInput, Prisma.WorkerUpdateWithoutPersonInput>, Prisma.WorkerUncheckedUpdateWithoutPersonInput>
}

export type Enumworker_roleFieldUpdateOperationsInput = {
  set?: $Enums.worker_role
}

export type WorkerCreateWithoutBookingsInput = {
  role?: $Enums.worker_role
  nickName: string
  password: string
  person: Prisma.PersonCreateNestedOneWithoutWorkerInput
}

export type WorkerUncheckedCreateWithoutBookingsInput = {
  personId: number
  role?: $Enums.worker_role
  nickName: string
  password: string
}

export type WorkerCreateOrConnectWithoutBookingsInput = {
  where: Prisma.WorkerWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkerCreateWithoutBookingsInput, Prisma.WorkerUncheckedCreateWithoutBookingsInput>
}

export type WorkerUpsertWithoutBookingsInput = {
  update: Prisma.XOR<Prisma.WorkerUpdateWithoutBookingsInput, Prisma.WorkerUncheckedUpdateWithoutBookingsInput>
  create: Prisma.XOR<Prisma.WorkerCreateWithoutBookingsInput, Prisma.WorkerUncheckedCreateWithoutBookingsInput>
  where?: Prisma.WorkerWhereInput
}

export type WorkerUpdateToOneWithWhereWithoutBookingsInput = {
  where?: Prisma.WorkerWhereInput
  data: Prisma.XOR<Prisma.WorkerUpdateWithoutBookingsInput, Prisma.WorkerUncheckedUpdateWithoutBookingsInput>
}

export type WorkerUpdateWithoutBookingsInput = {
  role?: Prisma.Enumworker_roleFieldUpdateOperationsInput | $Enums.worker_role
  nickName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  person?: Prisma.PersonUpdateOneRequiredWithoutWorkerNestedInput
}

export type WorkerUncheckedUpdateWithoutBookingsInput = {
  personId?: Prisma.IntFieldUpdateOperationsInput | number
  role?: Prisma.Enumworker_roleFieldUpdateOperationsInput | $Enums.worker_role
  nickName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorkerCreateWithoutPersonInput = {
  role?: $Enums.worker_role
  nickName: string
  password: string
  bookings?: Prisma.BookingCreateNestedManyWithoutWorkerInput
}

export type WorkerUncheckedCreateWithoutPersonInput = {
  role?: $Enums.worker_role
  nickName: string
  password: string
  bookings?: Prisma.BookingUncheckedCreateNestedManyWithoutWorkerInput
}

export type WorkerCreateOrConnectWithoutPersonInput = {
  where: Prisma.WorkerWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkerCreateWithoutPersonInput, Prisma.WorkerUncheckedCreateWithoutPersonInput>
}

export type WorkerUpsertWithoutPersonInput = {
  update: Prisma.XOR<Prisma.WorkerUpdateWithoutPersonInput, Prisma.WorkerUncheckedUpdateWithoutPersonInput>
  create: Prisma.XOR<Prisma.WorkerCreateWithoutPersonInput, Prisma.WorkerUncheckedCreateWithoutPersonInput>
  where?: Prisma.WorkerWhereInput
}

export type WorkerUpdateToOneWithWhereWithoutPersonInput = {
  where?: Prisma.WorkerWhereInput
  data: Prisma.XOR<Prisma.WorkerUpdateWithoutPersonInput, Prisma.WorkerUncheckedUpdateWithoutPersonInput>
}

export type WorkerUpdateWithoutPersonInput = {
  role?: Prisma.Enumworker_roleFieldUpdateOperationsInput | $Enums.worker_role
  nickName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bookings?: Prisma.BookingUpdateManyWithoutWorkerNestedInput
}

export type WorkerUncheckedUpdateWithoutPersonInput = {
  role?: Prisma.Enumworker_roleFieldUpdateOperationsInput | $Enums.worker_role
  nickName?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  bookings?: Prisma.BookingUncheckedUpdateManyWithoutWorkerNestedInput
}


/**
 * Count Type WorkerCountOutputType
 */

export type WorkerCountOutputType = {
  bookings: number
}

export type WorkerCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bookings?: boolean | WorkerCountOutputTypeCountBookingsArgs
}

/**
 * WorkerCountOutputType without action
 */
export type WorkerCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkerCountOutputType
   */
  select?: Prisma.WorkerCountOutputTypeSelect<ExtArgs> | null
}

/**
 * WorkerCountOutputType without action
 */
export type WorkerCountOutputTypeCountBookingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BookingWhereInput
}


export type WorkerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  personId?: boolean
  role?: boolean
  nickName?: boolean
  password?: boolean
  person?: boolean | Prisma.PersonDefaultArgs<ExtArgs>
  bookings?: boolean | Prisma.Worker$bookingsArgs<ExtArgs>
  _count?: boolean | Prisma.WorkerCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["worker"]>



export type WorkerSelectScalar = {
  personId?: boolean
  role?: boolean
  nickName?: boolean
  password?: boolean
}

export type WorkerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"personId" | "role" | "nickName" | "password", ExtArgs["result"]["worker"]>
export type WorkerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  person?: boolean | Prisma.PersonDefaultArgs<ExtArgs>
  bookings?: boolean | Prisma.Worker$bookingsArgs<ExtArgs>
  _count?: boolean | Prisma.WorkerCountOutputTypeDefaultArgs<ExtArgs>
}

export type $WorkerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Worker"
  objects: {
    person: Prisma.$PersonPayload<ExtArgs>
    bookings: Prisma.$BookingPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    personId: number
    role: $Enums.worker_role
    nickName: string
    password: string
  }, ExtArgs["result"]["worker"]>
  composites: {}
}

export type WorkerGetPayload<S extends boolean | null | undefined | WorkerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorkerPayload, S>

export type WorkerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorkerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorkerCountAggregateInputType | true
  }

export interface WorkerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Worker'], meta: { name: 'Worker' } }
  /**
   * Find zero or one Worker that matches the filter.
   * @param {WorkerFindUniqueArgs} args - Arguments to find a Worker
   * @example
   * // Get one Worker
   * const worker = await prisma.worker.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorkerFindUniqueArgs>(args: Prisma.SelectSubset<T, WorkerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorkerClient<runtime.Types.Result.GetResult<Prisma.$WorkerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Worker that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorkerFindUniqueOrThrowArgs} args - Arguments to find a Worker
   * @example
   * // Get one Worker
   * const worker = await prisma.worker.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorkerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorkerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkerClient<runtime.Types.Result.GetResult<Prisma.$WorkerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Worker that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkerFindFirstArgs} args - Arguments to find a Worker
   * @example
   * // Get one Worker
   * const worker = await prisma.worker.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorkerFindFirstArgs>(args?: Prisma.SelectSubset<T, WorkerFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorkerClient<runtime.Types.Result.GetResult<Prisma.$WorkerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Worker that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkerFindFirstOrThrowArgs} args - Arguments to find a Worker
   * @example
   * // Get one Worker
   * const worker = await prisma.worker.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorkerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorkerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkerClient<runtime.Types.Result.GetResult<Prisma.$WorkerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Workers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Workers
   * const workers = await prisma.worker.findMany()
   * 
   * // Get first 10 Workers
   * const workers = await prisma.worker.findMany({ take: 10 })
   * 
   * // Only select the `personId`
   * const workerWithPersonIdOnly = await prisma.worker.findMany({ select: { personId: true } })
   * 
   */
  findMany<T extends WorkerFindManyArgs>(args?: Prisma.SelectSubset<T, WorkerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Worker.
   * @param {WorkerCreateArgs} args - Arguments to create a Worker.
   * @example
   * // Create one Worker
   * const Worker = await prisma.worker.create({
   *   data: {
   *     // ... data to create a Worker
   *   }
   * })
   * 
   */
  create<T extends WorkerCreateArgs>(args: Prisma.SelectSubset<T, WorkerCreateArgs<ExtArgs>>): Prisma.Prisma__WorkerClient<runtime.Types.Result.GetResult<Prisma.$WorkerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Workers.
   * @param {WorkerCreateManyArgs} args - Arguments to create many Workers.
   * @example
   * // Create many Workers
   * const worker = await prisma.worker.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorkerCreateManyArgs>(args?: Prisma.SelectSubset<T, WorkerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Worker.
   * @param {WorkerDeleteArgs} args - Arguments to delete one Worker.
   * @example
   * // Delete one Worker
   * const Worker = await prisma.worker.delete({
   *   where: {
   *     // ... filter to delete one Worker
   *   }
   * })
   * 
   */
  delete<T extends WorkerDeleteArgs>(args: Prisma.SelectSubset<T, WorkerDeleteArgs<ExtArgs>>): Prisma.Prisma__WorkerClient<runtime.Types.Result.GetResult<Prisma.$WorkerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Worker.
   * @param {WorkerUpdateArgs} args - Arguments to update one Worker.
   * @example
   * // Update one Worker
   * const worker = await prisma.worker.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorkerUpdateArgs>(args: Prisma.SelectSubset<T, WorkerUpdateArgs<ExtArgs>>): Prisma.Prisma__WorkerClient<runtime.Types.Result.GetResult<Prisma.$WorkerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Workers.
   * @param {WorkerDeleteManyArgs} args - Arguments to filter Workers to delete.
   * @example
   * // Delete a few Workers
   * const { count } = await prisma.worker.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorkerDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorkerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Workers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Workers
   * const worker = await prisma.worker.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorkerUpdateManyArgs>(args: Prisma.SelectSubset<T, WorkerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Worker.
   * @param {WorkerUpsertArgs} args - Arguments to update or create a Worker.
   * @example
   * // Update or create a Worker
   * const worker = await prisma.worker.upsert({
   *   create: {
   *     // ... data to create a Worker
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Worker we want to update
   *   }
   * })
   */
  upsert<T extends WorkerUpsertArgs>(args: Prisma.SelectSubset<T, WorkerUpsertArgs<ExtArgs>>): Prisma.Prisma__WorkerClient<runtime.Types.Result.GetResult<Prisma.$WorkerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Workers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkerCountArgs} args - Arguments to filter Workers to count.
   * @example
   * // Count the number of Workers
   * const count = await prisma.worker.count({
   *   where: {
   *     // ... the filter for the Workers we want to count
   *   }
   * })
  **/
  count<T extends WorkerCountArgs>(
    args?: Prisma.Subset<T, WorkerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorkerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Worker.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorkerAggregateArgs>(args: Prisma.Subset<T, WorkerAggregateArgs>): Prisma.PrismaPromise<GetWorkerAggregateType<T>>

  /**
   * Group by Worker.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorkerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorkerGroupByArgs['orderBy'] }
      : { orderBy?: WorkerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorkerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Worker model
 */
readonly fields: WorkerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Worker.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  person<T extends Prisma.PersonDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PersonDefaultArgs<ExtArgs>>): Prisma.Prisma__PersonClient<runtime.Types.Result.GetResult<Prisma.$PersonPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  bookings<T extends Prisma.Worker$bookingsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Worker$bookingsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BookingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Worker model
 */
export interface WorkerFieldRefs {
  readonly personId: Prisma.FieldRef<"Worker", 'Int'>
  readonly role: Prisma.FieldRef<"Worker", 'worker_role'>
  readonly nickName: Prisma.FieldRef<"Worker", 'String'>
  readonly password: Prisma.FieldRef<"Worker", 'String'>
}
    

// Custom InputTypes
/**
 * Worker findUnique
 */
export type WorkerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Worker
   */
  select?: Prisma.WorkerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Worker
   */
  omit?: Prisma.WorkerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkerInclude<ExtArgs> | null
  /**
   * Filter, which Worker to fetch.
   */
  where: Prisma.WorkerWhereUniqueInput
}

/**
 * Worker findUniqueOrThrow
 */
export type WorkerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Worker
   */
  select?: Prisma.WorkerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Worker
   */
  omit?: Prisma.WorkerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkerInclude<ExtArgs> | null
  /**
   * Filter, which Worker to fetch.
   */
  where: Prisma.WorkerWhereUniqueInput
}

/**
 * Worker findFirst
 */
export type WorkerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Worker
   */
  select?: Prisma.WorkerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Worker
   */
  omit?: Prisma.WorkerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkerInclude<ExtArgs> | null
  /**
   * Filter, which Worker to fetch.
   */
  where?: Prisma.WorkerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Workers to fetch.
   */
  orderBy?: Prisma.WorkerOrderByWithRelationInput | Prisma.WorkerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Workers.
   */
  cursor?: Prisma.WorkerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Workers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Workers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Workers.
   */
  distinct?: Prisma.WorkerScalarFieldEnum | Prisma.WorkerScalarFieldEnum[]
}

/**
 * Worker findFirstOrThrow
 */
export type WorkerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Worker
   */
  select?: Prisma.WorkerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Worker
   */
  omit?: Prisma.WorkerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkerInclude<ExtArgs> | null
  /**
   * Filter, which Worker to fetch.
   */
  where?: Prisma.WorkerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Workers to fetch.
   */
  orderBy?: Prisma.WorkerOrderByWithRelationInput | Prisma.WorkerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Workers.
   */
  cursor?: Prisma.WorkerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Workers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Workers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Workers.
   */
  distinct?: Prisma.WorkerScalarFieldEnum | Prisma.WorkerScalarFieldEnum[]
}

/**
 * Worker findMany
 */
export type WorkerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Worker
   */
  select?: Prisma.WorkerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Worker
   */
  omit?: Prisma.WorkerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkerInclude<ExtArgs> | null
  /**
   * Filter, which Workers to fetch.
   */
  where?: Prisma.WorkerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Workers to fetch.
   */
  orderBy?: Prisma.WorkerOrderByWithRelationInput | Prisma.WorkerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Workers.
   */
  cursor?: Prisma.WorkerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Workers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Workers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Workers.
   */
  distinct?: Prisma.WorkerScalarFieldEnum | Prisma.WorkerScalarFieldEnum[]
}

/**
 * Worker create
 */
export type WorkerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Worker
   */
  select?: Prisma.WorkerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Worker
   */
  omit?: Prisma.WorkerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkerInclude<ExtArgs> | null
  /**
   * The data needed to create a Worker.
   */
  data: Prisma.XOR<Prisma.WorkerCreateInput, Prisma.WorkerUncheckedCreateInput>
}

/**
 * Worker createMany
 */
export type WorkerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Workers.
   */
  data: Prisma.WorkerCreateManyInput | Prisma.WorkerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Worker update
 */
export type WorkerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Worker
   */
  select?: Prisma.WorkerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Worker
   */
  omit?: Prisma.WorkerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkerInclude<ExtArgs> | null
  /**
   * The data needed to update a Worker.
   */
  data: Prisma.XOR<Prisma.WorkerUpdateInput, Prisma.WorkerUncheckedUpdateInput>
  /**
   * Choose, which Worker to update.
   */
  where: Prisma.WorkerWhereUniqueInput
}

/**
 * Worker updateMany
 */
export type WorkerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Workers.
   */
  data: Prisma.XOR<Prisma.WorkerUpdateManyMutationInput, Prisma.WorkerUncheckedUpdateManyInput>
  /**
   * Filter which Workers to update
   */
  where?: Prisma.WorkerWhereInput
  /**
   * Limit how many Workers to update.
   */
  limit?: number
}

/**
 * Worker upsert
 */
export type WorkerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Worker
   */
  select?: Prisma.WorkerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Worker
   */
  omit?: Prisma.WorkerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkerInclude<ExtArgs> | null
  /**
   * The filter to search for the Worker to update in case it exists.
   */
  where: Prisma.WorkerWhereUniqueInput
  /**
   * In case the Worker found by the `where` argument doesn't exist, create a new Worker with this data.
   */
  create: Prisma.XOR<Prisma.WorkerCreateInput, Prisma.WorkerUncheckedCreateInput>
  /**
   * In case the Worker was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorkerUpdateInput, Prisma.WorkerUncheckedUpdateInput>
}

/**
 * Worker delete
 */
export type WorkerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Worker
   */
  select?: Prisma.WorkerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Worker
   */
  omit?: Prisma.WorkerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkerInclude<ExtArgs> | null
  /**
   * Filter which Worker to delete.
   */
  where: Prisma.WorkerWhereUniqueInput
}

/**
 * Worker deleteMany
 */
export type WorkerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Workers to delete
   */
  where?: Prisma.WorkerWhereInput
  /**
   * Limit how many Workers to delete.
   */
  limit?: number
}

/**
 * Worker.bookings
 */
export type Worker$bookingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Booking
   */
  select?: Prisma.BookingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Booking
   */
  omit?: Prisma.BookingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingInclude<ExtArgs> | null
  where?: Prisma.BookingWhereInput
  orderBy?: Prisma.BookingOrderByWithRelationInput | Prisma.BookingOrderByWithRelationInput[]
  cursor?: Prisma.BookingWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BookingScalarFieldEnum | Prisma.BookingScalarFieldEnum[]
}

/**
 * Worker without action
 */
export type WorkerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Worker
   */
  select?: Prisma.WorkerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Worker
   */
  omit?: Prisma.WorkerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkerInclude<ExtArgs> | null
}
