
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Booking.ts'
export type * from './models/Person.ts'
export type * from './models/Room.ts'
export type * from './models/Worker.ts'
export type * from './commonInputTypes.ts'